-- Find the date of the first and last order

select MIN(nullif(order_date, '')::DATE) as first_order_date,
MAX(nullif(order_date, '')::DATE) as last_order_date,
AGE(MAX(nullif(order_date, '')::DATE), MIN(nullif(order_date, '')::DATE)) order_range_year
from fact_sales;

-- Find the youngest and the oldest customers

select MIN(nullif(birthdate, '')::DATE) as oldest_birthdate,
AGE(current_date,  MIN(nullif(birthdate, '')::DATE)) oldest_date,
MAX(nullif(birthdate, '')::DATE) as oldest_birthdate,
AGE(current_date,  MAX(nullif(birthdate, '')::DATE)) youngest_date
from dim_customers dc;

-----------------------------------------------------------------------

--Find the Total Sales
SELECT
	sum(sales_amount) total_sales
FROM
	fact_sales;
-- Find how many items are sold
SELECT
	sum(quantity)total_quantity
FROM
	fact_sales;
-- Find the average selling price
SELECT
	round(avg(price), 0) avg_price
FROM
	fact_sales;
-- Find the total number of orders
SELECT
	count(DISTINCT order_number)total_orders
FROM
	fact_sales;
-- Find the total number of products
SELECT
	count(product_name) total_products
FROM
	dim_products
	-- Find the total number of customers
SELECT
	count(customer_key) total_customers
FROM
	dim_customers;
-- Find the total number of customers that have placed an order
SELECT
	count(DISTINCT customer_key) total_products
FROM
	fact_sales;


-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' measure_name,
	sum(sales_amount) measure_value
FROM
	fact_sales
UNION ALL
SELECT 'Total Quantity',
	SUM(quantity) 
FROM
	fact_sales
UNION ALL 
SELECT 'Average Price',
	ROUND(AVG(price), 0) 
FROM
	fact_sales
UNION ALL
SELECT 'Total Nr. Orders',
	COUNT(DISTINCT order_number) 
FROM
	fact_sales
UNION ALL 
SELECT 'Total Nr. Products',
	COUNT(product_name) 
FROM
	dim_products
UNION ALL 
SELECT 'Total Nr. Customers',
	COUNT(customer_key) 
FROM
	dim_customers;


----------------------------------------------------------

-- Find total customers by country
SELECT
dc.country, 
COUNT(DISTINCT dc.customer_key) total_customers 
FROM dim_customers dc 
GROUP BY country 
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
dc.gender , 
COUNT(DISTINCT dc.customer_key) total_customers 
FROM dim_customers dc 
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total customers by country
SELECT
dp.category, 
COUNT(DISTINCT dp.product_key) total_products 
FROM dim_products dp  
GROUP BY dp.category 
ORDER BY total_products  DESC; 

-- What is the average costs in each category?
SELECT
dp.category, 
ROUND(AVG(dp.cost), 0) avg_cost
FROM dim_products dp  
GROUP BY dp.category 
ORDER BY avg_cost  DESC;

-- What is the total revenue generated for each category
SELECT
dp.category,
sum(t.sales_amount) total_revenue
FROM fact_sales t 
LEFT JOIN dim_products dp 
ON t.product_key = dp.product_key  
GROUP BY dp.category 
ORDER BY total_revenue  DESC; 

-- What is the total revenue generated by each customer
SELECT
dc.customer_key,
dc.first_name,
sum(t.sales_amount) total_revenue
FROM fact_sales t 
LEFT JOIN dim_customers dc 
ON t.customer_key  = dc.customer_key  
GROUP BY dc.customer_key, dc.first_name 
ORDER BY total_revenue  DESC; 

-- What is the distribution of sold items across countries?
SELECT
dc.country,
sum(t.quantity) total_sold_items
FROM fact_sales t 
LEFT JOIN dim_customers dc 
ON t.customer_key  = dc.customer_key  
GROUP BY dc.country
ORDER BY total_sold_items  DESC; 

------------------------------------------------------


-- Which 5 products generate the highest revenue?
SELECT
dp.product_name,
sum(t.sales_amount) total_revenue
FROM fact_sales t 
LEFT JOIN dim_products dp 
ON t.product_key = dp.product_key  
GROUP BY dp.product_name
ORDER BY total_revenue  DESC
LIMIT 5;

--Using the window function
SELECT * FROM (
	SELECT
	dp.product_name,
	sum(t.sales_amount) total_revenue,
	row_number() over(ORDER BY sum(t.sales_amount) desc) ranking
	FROM fact_sales t 
	LEFT JOIN dim_products dp 
	ON t.product_key = dp.product_key  
	GROUP BY dp.product_name
	)s WHERE s.ranking <=5;



--What are the  worst-performing products in term of sales?
SELECT
dp.product_name,
sum(t.sales_amount) total_revenue
FROM fact_sales t 
LEFT JOIN dim_products dp 
ON t.product_key = dp.product_key  
GROUP BY dp.product_name
ORDER BY total_revenue  
LIMIT 5


-- Find the top 10 customers who have generated the highest revenue
SELECT
dc.customer_key,
dc.first_name,
sum(t.sales_amount) total_revenue
FROM fact_sales t 
LEFT JOIN dim_customers dc 
ON t.customer_key  = dc.customer_key  
GROUP BY dc.customer_key, dc.first_name 
ORDER BY total_revenue  DESC
LIMIT 10;


-- The 3 customers with the fewest orders placed
SELECT
dc.customer_key,
dc.first_name,
count(DISTINCT t.order_number) total_orders
FROM fact_sales t 
LEFT JOIN dim_customers dc 
ON t.customer_key  = dc.customer_key  
GROUP BY dc.customer_key, dc.first_name 
ORDER BY total_orders
LIMIT 3;
